### ISSUE TITLE
signRequest fails after upgrade from v1.4.7 to v1.4.8

### ISSUE THREAD

**Issue by mrkvon** [fedify-dev/fedify#222]
Hello! I tried out fedify, starting with version 1.4.7, for [a new project](https://github.com/soap-opera/soap-opera). So far I use it for signing and verifying requests with HTTP Signatures.

### Actual behavior

A few moments ago I upgraded from v1.4.7 to v1.4.8 and I start getting error when calling `signRequest()` in my tests:

```
TypeError: buffer.buffer.transfer is not a function
 ❯ detach node_modules/@fedify/fedify/esm/deps/jsr.io/@std/encoding/1.0.8/_common_detach.js:10:43
 ❯ encodeBase64 node_modules/@fedify/fedify/esm/deps/jsr.io/@std/encoding/1.0.8/base64.js:54:25
 ❯ signRequestInternal node_modules/@fedify/fedify/esm/sig/http.js:63:42
 ❯ node_modules/@fedify/fedify/esm/sig/http.js:25:28
 ❯ signRequest node_modules/@fedify/fedify/esm/sig/http.js:23:12
 ❯ src/test/get-followed.spec.ts:121:27
```

So I'm guessing this is a bug or a breaking change. For the time being I just revert back to v1.4.7.

### Expected behavior

`signRequest` keeps working after an upgrade.

### Context

Failing snippet:

```ts
    const request = new Request(
      new URL(`/users/testuser/inbox`, appConfig.baseUrl),
      {
        method: 'POST',
        headers: { 'content-type': 'application/activity+json' },
        body: JSON.stringify(validBody),
      },
    )

    const signedRequest = await signRequest( // this throws after upgrade to v1.4.8
      request,
      keys.privateKey,
      new URL('https://example.local/actor#main-key'),
    )

    const response = await fetch(signedRequest)

    expect(response.status).toBe(200)
```

**Comment by dahlia** [comment]
Hmm, strange. What kind of JavaScript runtime do you use? Node.js? Bun?

**Comment by dahlia** [comment]
Okay, it seems a bug made in [@std/encoding v1.0.8](https://jsr.io/@std/encoding@1.0.8), so I'll pin it to [v1.0.7](https://jsr.io/@std/encoding@1.0.7).

**Comment by dahlia** [comment]
The fix was shipped with [v1.4.9](https://github.com/fedify-dev/fedify/releases/tag/1.4.9).

**Comment by mrkvon** [comment]
I can confirm that the issue is fixed in v1.4.9.

Thank you for such prompt addressing of the issue! 🚀
